# Change these first
owner: PhenixHartogh # Your GitHub organization or username, where this repository lives
repo: status.phenixhartogh.com.au # The name of this repository

sites:
  - name: Main Website
    url: https://phenixhartogh.com.au
  - name: Status Website
    url: https://status.phenixhartogh.com.au

status-website:
  # Add your custom domain name, or remove the `cname` line if you don't have a domain
  # Uncomment the `baseUrl` line if you don't have a custom domain and add your repo name there
  cname: status.phenixhartogh.com.au
  # baseUrl: /your-repo-name
  logoUrl: https://raw.githubusercontent.com/upptime/upptime.js.org/master/static/img/icon.svg
  name: PH Status
  introTitle: "The status page that monitors all PH services."
  introMessage: This is a status page which uses **real-time** data to monitor all PH services with only Github!
  navbar:
    - title: Status
      href: /
    - title: GitHub
      href: https://github.com/$OWNER/$REPO

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
